project_id = "mxdupkbpxjcfxdgrwknp"

[functions.check-due-invoices]
verify_jwt = false

[functions.process-contract]
verify_jwt = false

[functions.generate-contract-pdf]
verify_jwt = false

[functions.sync-chatbot-knowledge]
verify_jwt = false

[functions.sales-agent]
verify_jwt = false

[functions.routing-agent]
verify_jwt = false

[functions.support-tech-agent]
verify_jwt = false

[functions.support-financial-agent]
verify_jwt = false

[functions.ixc-list-contracts]
verify_jwt = true

[functions.nps-webhook]
verify_jwt = false

[functions.automacao-agent]
verify_jwt = false

[functions.telemedicina-agent]
verify_jwt = false
