import type { SupabaseClient } from '@supabase/supabase-js';

// Override types for the autogenerated Supabase client so that
// application code can compile even when database types are minimal.
declare module '@/integrations/supabase/client' {
  const supabase: SupabaseClient<any, any, any>;
  export { supabase };
}
